#!/bin/bash

git add .

echo 'Enter the commit message:'
read commitMessage

git commit -m "$commitMessage"

echo 'Enter the branch name (or leave empty for default "git push"):'
read branch

if [ -z "$branch" ]; then
  git push
else
  git push origin "$branch"
fi
