#!/bin/bash

git add .

echo 'Enter the commit message:'
read commitMessage

git commit -m "$commitMessage"

echo "Would you like to chmod a file? (y/n)"
read choice

if [ "$choice" == "y" ]; then
  echo 'Enter the filename to chmod:'
  ls
  read filename
  chmod +x "$filename"
fi

read branch

git push origin $branch

