#!/bin/bash

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

git add .

echo -e "${YELLOW}Enter the commit message:${NC}"
read commitMessage

git commit -m "$commitMessage"

echo "${GREEN}Enter the branch name (or leave empty for default "git push")${NC}"
read branch

if [ -z "$branch" ]; then
  git push
else
  git push origin "$branch"
fi
